/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.br.ifnmg.trabalho2.kesia.apresentacao;

import edu.br.ifnmg.trabalho2.kesia.entidade.Usuario;
import edu.br.ifnmg.trabalho2.kesia.excecao.MerciException;
import edu.br.ifnmg.trabalho2.kesia.excecao.ValidarLoginESenhaException;
import edu.br.ifnmg.trabalho2.kesia.excecao.ValidarSenhaAlterarSenhaException;
import edu.br.ifnmg.trabalho2.kesia.excecao.ValidarSenhaUsuarioConfirmarSenhaException;
import edu.br.ifnmg.trabalho2.kesia.negocio.UsuarioBO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Késia Correiia
 */
public class LoginForm extends javax.swing.JFrame {
    Usuario usuarioLogin = new Usuario();
  


    /**
     * Creates new form LoginComUsuario
     */
    public LoginForm() {
       initComponents();
       setLocationRelativeTo( null );  
       desabilitarBotoes();
    }
    
    private void desabilitarBotoes(){
        btnLogoff.setEnabled(false);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(false);
        lblConfirmarSenha.setEnabled(false);
        txtConfirmarSenha.setEnabled(false); 
        btnCancelar.setEnabled(false);
        mnuGestao.setEnabled(false);
        mnuVendas.setEnabled(false);
        mnuOpcoes.setEnabled(false);
        mnuAjuda.setEnabled(true);
    }
    
    private void habilitarBotoes(){
        btnLogin.setEnabled(false);
        btnLogoff.setEnabled(true);
        btnAlterarSenha.setEnabled(true);
        btnConfirmarSenha.setEnabled(false);
        txtConfirmarSenha.setEnabled(false); 
        txtLogin.setEnabled(false); 
        txtSenha.setEnabled(false); 
        lblConfirmarSenha.setEnabled(false);
        lblSenha.setEnabled(false);
        lblLogin.setEnabled(false);
        mnuGestao.setEnabled(true);
        mnuOpcoes.setEnabled(true);
        mnuAjuda.setEnabled(true);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogoff = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnConfirmarSenha = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuGestao = new javax.swing.JMenu();
        mnuItemUsuario = new javax.swing.JMenu();
        mnuItemCadastroUsuario = new javax.swing.JMenuItem();
        mnuItemConsultaUsuarios = new javax.swing.JMenuItem();
        mnuItemFornecedores = new javax.swing.JMenuItem();
        mnuItemMercadorias = new javax.swing.JMenuItem();
        mnuItemPedidosCompra = new javax.swing.JMenuItem();
        mnuItemEstoque = new javax.swing.JMenuItem();
        mnuItemAbrirCaixa = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();
        mnuItemSobre = new javax.swing.JMenuItem();
        mnuOpcoes = new javax.swing.JMenu();
        mnuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Merci");

        btnLogoff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/sair.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/entrar.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAlterarSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/key.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnConfirmarSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/key_go.png"))); // NOI18N
        btnConfirmarSenha.setText("Confirmar Senha");
        btnConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSenhaActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogin.setText("Login:");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        lblConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmarSenha.setText("Confirmar Senha:");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/fechar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin)
                            .addComponent(lblSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtLogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogoff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblConfirmarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmarSenha)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mnuGestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/opções.png"))); // NOI18N
        mnuGestao.setText("Gestão");
        mnuGestao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/menu_usuario.png"))); // NOI18N
        mnuItemUsuario.setText("Usários");

        mnuItemCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuItemCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastroUsuario.setText("Cadastro");
        mnuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        mnuItemUsuario.add(mnuItemCadastroUsuario);

        mnuItemConsultaUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuItemConsultaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemConsultaUsuarios.setText("Consultar");
        mnuItemConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaUsuariosActionPerformed(evt);
            }
        });
        mnuItemUsuario.add(mnuItemConsultaUsuarios);

        mnuGestao.add(mnuItemUsuario);

        mnuItemFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mnuItemFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/revendedores.png"))); // NOI18N
        mnuItemFornecedores.setText("Fornecedores");
        mnuGestao.add(mnuItemFornecedores);

        mnuItemMercadorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnuItemMercadorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/produto.png"))); // NOI18N
        mnuItemMercadorias.setText("Mercadorias");
        mnuGestao.add(mnuItemMercadorias);

        mnuItemPedidosCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuItemPedidosCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/pedidos.png"))); // NOI18N
        mnuItemPedidosCompra.setText("Pedidos de Compra");
        mnuGestao.add(mnuItemPedidosCompra);

        mnuItemEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuItemEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/sabores.png"))); // NOI18N
        mnuItemEstoque.setText("Estoque");
        mnuGestao.add(mnuItemEstoque);

        mnuItemAbrirCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuItemAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/monitor_go.png"))); // NOI18N
        mnuItemAbrirCaixa.setText("Abrir Caixa");
        mnuGestao.add(mnuItemAbrirCaixa);

        mnuPrincipal.add(mnuGestao);

        mnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/vendas.png"))); // NOI18N
        mnuVendas.setText("Vendas");
        mnuVendas.setDelay(300);
        mnuVendas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        mnuVendas.setIconTextGap(0);
        mnuVendas.setMaximumSize(new java.awt.Dimension(59, 32767));
        mnuVendas.setMinimumSize(new java.awt.Dimension(49, 19));
        mnuVendas.setPreferredSize(new java.awt.Dimension(49, 29));
        mnuPrincipal.add(mnuVendas);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/help.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/information.png"))); // NOI18N
        mnuItemSobre.setText("Sobre");
        mnuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuItemSobre);

        mnuPrincipal.add(mnuAjuda);

        mnuOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/opções (2).png"))); // NOI18N
        mnuOpcoes.setText("Opções");

        mnuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/br/ifnmg/trabalho2/kesia/apresentacao/icones/sair.png"))); // NOI18N
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuItemSair);

        mnuPrincipal.add(mnuOpcoes);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
        this.habilitarCamposAlterarSenha();
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        // TODO add your handling code here:
        this.sairSistema();
    }//GEN-LAST:event_mnuItemSairActionPerformed
    
    private void sairSistema(){
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Sair do Sistema?","ATENÇÃO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            System.exit(0);
        }
    }
    
    private void mnuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        CadastroUsuarioForm cadastroUsuario= new CadastroUsuarioForm();
        cadastroUsuario.setVisible(true);
        
    }//GEN-LAST:event_mnuItemCadastroUsuarioActionPerformed

    private void mnuItemConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaUsuariosActionPerformed
        // TODO add your handling code here:
        ConsultaUsuariosForm consultaUsuariosForm = new ConsultaUsuariosForm();
        consultaUsuariosForm.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaUsuariosActionPerformed

    private void mnuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSobreActionPerformed
        // TODO add your handling code here:
        AjudaMerciForm ajudaMerciForm = new AjudaMerciForm();
        ajudaMerciForm.setVisible(true);
    }//GEN-LAST:event_mnuItemSobreActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        try {
            this.login();
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        
            // TODO add your handling code here:
        this.dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
            
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void btnConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSenhaActionPerformed
        // TODO add your handling code here:
        this.confirmarSenha();
    }//GEN-LAST:event_btnConfirmarSenhaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.desabilitarCamposAlterarSenha();
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed


       private void confirmarSenha(){
        try{
            if(txtSenha.getText().trim().isEmpty() || txtConfirmarSenha.getText().trim().isEmpty()){
            String mensagemErro = "Favor preencher os campos!!\n";
            JOptionPane.showMessageDialog(this, mensagemErro, "Confirma Senha", JOptionPane.ERROR_MESSAGE);
        }else{  
            this.lerDadosAlterarSenha(); 
            UsuarioBO  usuarioBO = new UsuarioBO();
            usuarioBO.atualizarDadosSenha(usuarioLogin);
            this.limparCamposAlterarSenha();
            this.desabilitarCamposAlterarSenha();
            exibirMensagemSucesso("Senha alterada com sucesso!", "Alterar senha de usuário");
        }
        }catch(MerciException e){
            String mensagem = "Erro ao alterar senha!!\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Aterar Senha", JOptionPane.ERROR_MESSAGE);
        }catch(SQLException e){
            exibirMensagemErro("Erro desconhecido contate com administrador", "Cadastrar login usuário");
        }
    }
   
    private void exibirMensagemErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    private void exibirMensagemSucesso(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
  
    
     public void login() throws SQLException {
       try{
            if(txtLogin.getText().trim().isEmpty() || txtSenha.getText().trim().isEmpty()){
            String mensagemErro = "Favor preencher os campos!!\n";
            JOptionPane.showMessageDialog(this, mensagemErro, "Login", JOptionPane.ERROR_MESSAGE);
        }else{  
            this.lerDados();
            UsuarioBO usuarioBO = new UsuarioBO();
            usuarioLogin = usuarioBO.login(usuarioLogin.getLogin(),usuarioLogin.getSenha());    
            if(usuarioLogin == null){
                throw new ValidarLoginESenhaException();
            }else{ 
                mensagemLogin("Você logou como: " + usuarioLogin.getNome(), "Login usuário");
               this.limparCamposTela();
               this.habilitarCampos();
            }
        }
       }catch(MerciException e){
            String mensagem = "Erro ao logar!!\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Login", JOptionPane.ERROR_MESSAGE);
       }
    }
   
    public void mensagemLogin(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
       private void habilitarCamposAlterarSenha(){
           txtLogin.setEnabled(false);
           txtSenha.setEnabled(true);
           txtConfirmarSenha.setEnabled(true);
           lblSenha.setEnabled(true);
           lblConfirmarSenha.setEnabled(true);
           btnAlterarSenha.setEnabled(false);
           btnConfirmarSenha.setEnabled(true);
           btnCancelar.setEnabled(true);
           this.txtLogin.setText(usuarioLogin.getLogin());
       }
    
    private void limparCamposTela(){
        txtLogin.setText("");
        txtSenha.setText("");
    }
    
    private void limparCamposAlterarSenha(){
        txtSenha.setText("");
        txtConfirmarSenha.setText("");
    }
    
    private void desabilitarCamposAlterarSenha(){
        btnConfirmarSenha.setEnabled(false);
        txtSenha.setEnabled(false);
        txtConfirmarSenha.setEnabled(false);
        lblSenha.setEnabled(false);
        lblConfirmarSenha.setEnabled(false);
        btnAlterarSenha.setEnabled(true);
    }
    
     private void lerDados() {
       usuarioLogin.setLogin(txtLogin.getText().trim());
       usuarioLogin.setSenha(txtSenha.getText().trim());
    }
     
    private void lerDadosAlterarSenha(){
       usuarioLogin.setSenha(txtSenha.getText().trim());
       usuarioLogin.setConfirmaSenha(txtConfirmarSenha.getText().trim()); 
       if(usuarioLogin.getSenha() == null ? usuarioLogin.getConfirmaSenha() != null : !usuarioLogin.getSenha().equals(usuarioLogin.getConfirmaSenha())){
           throw new ValidarSenhaUsuarioConfirmarSenhaException();
       }
       
    }
    
   private void habilitarCampos() throws SQLException{
       UsuarioBO usuarioBO = new UsuarioBO();
       usuarioBO.buscarPorTipoUsuario(usuarioLogin.getTipoUsuario());
        if(usuarioLogin.getTipoUsuario().equals("Gerente")){
            mnuItemUsuario.setVisible(true);
            mnuItemFornecedores.setEnabled(false);
            mnuItemMercadorias.setEnabled(false);
            mnuItemPedidosCompra.setEnabled(false);
            mnuItemEstoque.setEnabled(false);
            mnuItemAbrirCaixa.setVisible(true);
            mnuVendas.setEnabled(false);
            mnuAjuda.setVisible(true);
            mnuOpcoes.setVisible(true);
            habilitarBotoes();
         
        }else if(usuarioLogin.getTipoUsuario().equals("Gestor de Compras")){
            mnuItemUsuario.setEnabled(false);
            mnuItemFornecedores.setVisible(true);
            mnuItemMercadorias.setVisible(true);
            mnuItemPedidosCompra.setVisible(true);
            mnuItemEstoque.setEnabled(false);
            mnuItemAbrirCaixa.setEnabled(false);
            mnuGestao.setEnabled(true);
            mnuVendas.setEnabled(false);
            mnuAjuda.setVisible(true);
            mnuOpcoes.setVisible(true);
            habilitarBotoes();
        }else if(usuarioLogin.getTipoUsuario().equals("Gestor de Estoque")){
            mnuItemUsuario.setEnabled(false);
            mnuItemFornecedores.setEnabled(false);
            mnuItemMercadorias.setEnabled(false);
            mnuItemPedidosCompra.setEnabled(false);
            mnuItemEstoque.setVisible(true);
            mnuItemAbrirCaixa.setEnabled(false);
            mnuGestao.setEnabled(true);
            mnuVendas.setEnabled(false);
            mnuAjuda.setVisible(true);
            mnuOpcoes.setVisible(true);
            habilitarBotoes();
        }else{
            mnuItemUsuario.setEnabled(false);
            mnuItemFornecedores.setEnabled(false);
            mnuItemMercadorias.setEnabled(false);
            mnuItemPedidosCompra.setEnabled(false);
            mnuItemEstoque.setEnabled(false);
            mnuItemAbrirCaixa.setEnabled(false);
            mnuGestao.setEnabled(true);
            mnuVendas.setEnabled(true); 
            mnuAjuda.setVisible(true);
            mnuOpcoes.setVisible(true);
            habilitarBotoes();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuGestao;
    private javax.swing.JMenuItem mnuItemAbrirCaixa;
    private javax.swing.JMenuItem mnuItemCadastroUsuario;
    private javax.swing.JMenuItem mnuItemConsultaUsuarios;
    private javax.swing.JMenuItem mnuItemEstoque;
    private javax.swing.JMenuItem mnuItemFornecedores;
    private javax.swing.JMenuItem mnuItemMercadorias;
    private javax.swing.JMenuItem mnuItemPedidosCompra;
    private javax.swing.JMenuItem mnuItemSair;
    private javax.swing.JMenuItem mnuItemSobre;
    private javax.swing.JMenu mnuItemUsuario;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuVendas;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
